name: Upload to S3

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install AWS CLI
        run: pip install --upgrade awscli

      - name: Find today's zip file
        id: find_zip
        run: |
          today=$(date +"%Y-%m-%d")
          latest_file=$(ls -t *.zip | grep $today | head -n1)

      - name: Upload to S3
        run: |
          aws s3 cp api-2.0.0.95.zip ${AWS_S3_BUCKET}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}