name: Upload to S3

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install awscli

      - name: Fetch latest commit SHA
        id: latest_commit
        run: echo "::set-output name=sha::$(git rev-parse HEAD)"

      - name: Fetch latest zip file
        id: latest_zip
        run: |
          git archive ${{ steps.latest_commit.outputs.sha }} --format=zip --output=latest.zip

      - name: Upload latest build to S3
        run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        run: aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws configure set AWS_S3_BUCKET ${{ secrets.AWS_S3_BUCKET_NEW }}
        # run: aws configure set default.region us-east-1
run: aws s3 cp latest.zip s3://$AWS_S3_BUCKET/