name: Upload Build to S3

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the upload

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Replace with your desired Python version

      - name: Install dependencies
        run: pip install awscli

      - name: Upload latest build to S3
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set AWS_S3_BUCKET ${{ secrets.AWS_S3_BUCKET_NEW }}
          aws configure set default.region us-east-1
          LATEST_FILE=$(ls -t test-s3-deployment/*.zip | head -n1)
          aws s3 cp $LATEST_FILE s3://$AWS_S3_BUCKET/