name: Upload to S3

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install AWS CLI
        run: pip install --upgrade awscli

      - name: Fetch latest commit SHA
        id: latest_commit
        run: echo "::set-output name=sha::$(git rev-parse HEAD)"

      - name: Fetch latest zip file
        id: latest_zip
        run: |
          git archive ${{ steps.latest_commit.outputs.sha }} --format=zip --output=latest.zip

      - name: Upload latest build to S3
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set AWS-S3-BUCKET ${{ secrets.AWS_S3_BUCKET }}
          aws configure set default.region us-east-1
          LATEST_FILE=$(ls -t test-s3-deployment/*.zip | head -1)
          aws s3 cp $LATEST_FILE s3://${AWS_S3_BUCKET}/
          #aws s3 cp latest.zip s3://${AWS-S3-BUCKET}/