name: upload artifacts from github to s3

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with: 
        #args: --acl public-read --follow-symlinks --delete --exclude '.git*/*'
        run:  |
          latest_file=$(ls -t *.zip | head -n1)
          aws s3 cp ${latest_file} s3://${AWS_S3_BUCKET}/ --acl public-read

      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}