name: Upload Build to S3

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install awscli -y

      - name: Build and zip files
        run: |
          # Replace with your build commands
          npm run build
          zip -r build.zip build

      - name: Upload to S3
        run: |
          aws s3 cp build.zip s3://cf-templates-1krz2x79gf5ml-us-east-1/build/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
